name = "mobcrafter-api"
main = "src/index.js"
compatibility_date = "2025-12-16"

# D1
[[d1_databases]]
binding = "SUBMISSIONS_DB"
database_name = "mobcrafter_portal"
database_id = "f2bf5b67-af2a-47e0-929c-a3c7f1a09743"

# R2
[[r2_buckets]]
binding = "UPLOADS_BUCKET"
bucket_name = "mobcrafter-uploads"
